version: '3.8'

volumes:
    database:
        external: true

networks:
  bridge:

services:
  frontend:
    container_name: frontend
    build:
      context: ./meter_monitor_frontend
    ports:
      - 8080:8080
    networks:
      - bridge
    # volumes:
    #   - .:/usr/src/app:cached

  backend:
    container_name: backend
    build: 
      context: ./meter_monitor_backend
    restart: always
    ports:
      - 3000:3000
    networks:
      - bridge
    # volumes:
    #   - ./meter_monitor_backend:/usr/src/app:cached

  db:
    container_name: db
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: monitorDam
    ports:
      - 27017:27017
    volumes:
      # - database:/data/db
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro # for init user & database
    networks:
      - bridge

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@db:27017/
      # ME_CONFIG_SITE_BASEURL: /mongoexpress/
    ports:
      - 8081:8081
    links:
      - db
    depends_on:
      - db
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - bridge
    
  nginx:
    container_name: nginx
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - frontend
      - backend
      - db
    volumes:
      - ./certbot/www:/var/www/certbot:ro
      - ./certbot/conf:/etc/nginx/ssl:ro
      - ./certbot/dhparam:/etc/nginx/dhparam:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - bridge
    

  mongo-seed:
    image: mongo_seed
    build: 
      context: ./mongo_seed
      dockerfile: Dockerfile
    links:
      - db
    depends_on:
      - db
    networks:
      - bridge