version: '3.8'

volumes:
    database:
        external: true

networks:
  bridge:

services:
  frontend:
    container_name: frontend
    build:
      context: ./meter_monitor_frontend
    ports:
      - 8080:8080
    networks:
      - bridge
    # volumes:
    #   - .:/usr/src/app:cached

  backend:
    container_name: backend
    build: 
      context: ./meter_monitor_backend
    ports:
      - 3000:3000
    networks:
      - bridge
    # volumes:
    #   - ./meter_monitor_backend:/usr/src/app:cached

  db:
    container_name: db
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: monitorDam
    ports:
      - 27017:27017
    volumes:
      - database:/data/db
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro # for init user & database
    networks:
      - bridge

  mongo-express:
    image: mongo-express:latest
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@db:27017/monitorDam
    networks:
      - bridge

  mongo-seed:
    image: mongo_seed
    build: 
      context: ./mongo_seed
      dockerfile: Dockerfile
    links:
      - db
    depends_on:
      - db
    networks:
      - bridge