version: '3.8'

services:
  backend:
    container_name: backend
    build: 
      context: ./
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app:cached
  db:
    container_name: db
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - database:/data/db

volumes:
    database:
        external: true